// Generated by CoffeeScript 1.6.3
var arr, obj;

require("sugar");

require("./dirty");

arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 2, 2, 4];

obj = {
  mostly_no: ['no', 'no', 'no', 'yes'],
  mostly_yes: ['yes', 'yes', 'yes', 'no', 'yes', 'maybe'],
  really_yes: ['yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes'],
  one_yes: ['yes'],
  mixed: ['yes', 'no'],
  mixed2: ['yes', 'yes', 'no', 'no']
};

arr = ['yes', 'fun', 'cool'];

console.log(arr.hasmap());
