// Generated by CoffeeScript 1.6.3
var arr, obj, x;

require("sugar");

require("./dirty");

obj = {
  fun: 3,
  cool: 2
};

arr = [1, 2, 3, 4, 5, 6];

x = 4.;

console.log(x.randomto(5));

/*
//@ sourceMappingURL=test.map
*/
