// Generated by CoffeeScript 1.6.3
var obja, objb, objb2, objc;

require("sugar");

require("./dirty");

obja = {
  fun: 1,
  cool: [1, 9]
};

objb = {
  fun: 3,
  cool: 2
};

objb2 = {
  fun: 3,
  cool: 1
};

objc = {
  fun: "cc",
  cool: "c"
};

console.log(Object.to_a(objc));
